# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    # Official Postgres image from DockerHub (we use the last version)
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: auth # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
